### ISSUE TITLE
Central Remote Admin Server

### ISSUE THREAD

**Issue by cookdoeyl** [cook-company/kiosk#285]
I have multiple computers with the Kiosk app running, and it would be great if I could specify a central remote administration server all of the apps can point back (or "phone home") to. I would be great since my computers are set to DHCP, and I can't change it without my admin's approval. So the remote admin IP address is always changing.

**Comment by daveilers** [comment]
I'd like something similar for a different reason, doing admin over plain http is a security concern. 

I'd like to make a kiosk admin page that the kiosk can query via https to get their config. Perhaps setup gives them an opportunity to set a config url and the kiosk registers a UUID with that remote server which it can get its url in json format from. Perhaps the lazy can even just do it via a GIST or jsonstore?

**Comment by knobo** [comment]
A small change could change the addon to be configured from policy settings #37
A seperate release with configuration of url, admin username and password, and some of the options would be nice.

**Comment by matt-cook** [comment]
This should be resolved by our new Kiosk Device Management Dashboard: https://dashboard.kiosk.cook.company/
