### ISSUE TITLE
Crashes On Save 

### ISSUE THREAD

**Issue by jackculton** [cook-company/kiosk#288]
Kiosk app on Chromebook, Box, and Bit crashes once you click save. Upon reopening the app the whole screen is black, CTRL+W, and then reopen the app and then it works. This also happens during the daily reset. Please help! This is most likely an issue with one of the newer versions of Chrome but it has been happening all year and I have been waiting for a fix. Is this happening to anyone else? The device I am using is enrolled in an enterprise...

**Comment by matt-cook** [comment]
@jackculton can you try installing the development release of the application and let me know if you still see the issue? https://chrome.google.com/webstore/detail/fainheghnahlfhpbafeknkbgogodmbfl

I haven't been able to reproduce this issue on a ChromeOS device, but it's definitely something I'd like to address immediately if it's occurring for other folks.

**Comment by jackculton** [comment]
@matt-cook Here is a video I recorded launching the app you linked to: [https://goo.gl/eb6HVU](https://goo.gl/eb6HVU)
This could be an issue with the permissions the app type has under my admin policy, however, I can get it to work eventually. I will try to launch both apps on a non-managed device. Maybe it has something to do with the URL that I am using? Let me know your thoughts...
