### ISSUE TITLE
Ubuntu Chromium Kiosk seems to delete cache

### ISSUE THREAD

**Issue by abesherman** [cook-company/kiosk#289]
it use to work in Windows, however it seems that setting it up in Ubuntu once i close the browser it will delete all cache, we use a hash code for all our devices, and we will need to log them back in after a computer restart and it dose not work for us, any sluchion?

**Comment by matt-cook** [comment]
Closing since we now have a native linux version: https://kiosk.cook.company/get-started please create a new issue if you continue to see issues with version 9.0.4 or later.
