### ISSUE TITLE
Leave the fullscreen mode when the escape key is pressed

### ISSUE THREAD

**Issue by thierryg** [cook-company/kiosk#297]
Hi guys,

While my application's kiosk is running in fullscreen mode, when i am pressing the escape key, the application leave the fullscreen and become a simple popup resized in 

I have seen within the code that the ESC ket (key 27) is catched but i have the problem anyway.

Does any other people can reproduce my issue?

Thanks in advance.

BR
Thierry

**Comment by matt-cook** [comment]
Closing due to age. If you're still seeing a problem with version 9.0.4 (https://kiosk.cook.company/get-started) or later please create a new ticket.
